### PR TITLE
added a protocol  profit feature

### PR DESCRIPTION
**Pull request by ddmilado**
Created a profit feature. The Smart Contract sends 96% of the total winning to the Raffle winner address and sends the remaining 4%  as "Profit" to a designated protocol address.

### CODE REVIEW

**Review by krakxn — COMMENTED** [review]
I do not find this relevant as I recall Patrick mentioning the "prize" to be 100% w/o commissions; nonetheless, it could be a good sample for such a functionality.

**Comment by ddmilado** [comment]
Exactly, it's just the option. I did use it on a mainnet project tho.

**Comment by PatrickAlphaC** [comment]
Cool idea! To keep this repo similar to the video though, we are going to close it. Thanks!

**Comment by ddmilado** [comment]
Makes sense 😀

**Pull request closed without merging**
